name: MythicTotem
version: '${project.version}'
main: cn.superiormc.mythictotem.MythicTotem
api-version: 1.14
folia-supported: true
softdepend:
  - WorldGuard
  - Towny
  - Dominion
  - Lands
  - PlotSquared
  - BentoBox
  - Residence
  - GriefPrevention
  - HuskTowns
  - HuskClaims
  - MMOItems
  - MythicLib
  - ItemsAdder
  - Vault
  - PlayerPoints
  - GamePoints
  - Oraxen
  - EcoItems
  - EcoArmor
  - PlaceholderAPI
  - UltraEconomy
  - CoinsEngine
  - RedisEconomy
  - EcoBits
  - MythicMobs
  - VotingPlugin
  - ExecutableItems
  - MythicChanger
commands:
  mythictotem:
    aliases:
      - "mt"
      - "totem"
    usage: "/mythictotem"
    description: "MythicTotem Main Command."
